import style from './MainLayout.module.css';
import { NavBar } from '../NavBar';
import Head from 'next/head'
// import { Inter } from 'next/font/google';
import { PropsWithChildren } from 'react';

export const MainLayouts: React.FC<PropsWithChildren> = ({ children }) => {
    return (
        <>
          {/* Permite agregar informacion a <head> */}
          <Head>
            <title>Home</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <NavBar/>
    
          {/* <main className={`${style.main} ${inter.className}`}> */}
          <main className={`${style.main}`}>

            { children }

          </main>
        </>
      ) 
}
